### PR TITLE
:sparkles: Implements deconstruct method

### PR DESCRIPTION
**Pull request by tiagor87**
Implement deconstruct method to make it easy to retrieve values.

### CODE REVIEW

**Review by AraHaan — APPROVED** [review]

**Comment by mcintyre321** [comment]
Sorry, I don't think this is a feature I want to include in the library. Getting values out without matching each case rather defeats the point of a OneOf, as I see it.

**Comment by Drizin** [comment]
If anyone else is also interested in deconstructors: 

https://github.com/Drizin/OneOf.DeconstructorExtensions

This library extends `OneOf<>` and `OneOfBase<>` with methods to deconstruct them into the underlying types. The major non-trivial addition here is that non-nullable value types will be automatically converted into nullable types, which means that deconstructing the Tuple will always return a single non-null value (all other values will be null), respecting the same semantic of union-types.
There are also extensions to convert to `Tuple<>` or `ValueTuple<>`

**Comment by ppasieka** [comment]
> Sorry, I don't think this is a feature I want to include in the library. Getting values out without matching each case rather defeats the point of a OneOf, as I see it.

That is an interesting argument, considering that the library supports methods like `IsT1` and `AsT1`, which says: "Yeah, I know that I have to check the results by myself"

**Comment by mcintyre321** [comment]
Yes, I regret putting them in there in retrospect.

**Pull request closed without merging**
