### PR TITLE
Added FsOneOf

### PR DESCRIPTION
**Pull request by TKilFree**
This is a separate .fsproj which introduces as many FsOneOf types as there are OneOf types. Each FsOneOf type has members to convert from a C# OneOf and convert to a C# OneOf.

These types exist to help interop when consuming C# OneOfs in an F# library (something I've ended up doing recently). This is possible with OneOfs as they are, but a little bit painful since you can't do nice pattern matching or anything.

### CODE REVIEW

**Comment by mcintyre321** [comment]
This looks great! Should I be publishing this as a Nuget package? It looks like it targets 4.5.2 - is it possible to make it target multiple frameworks like the other OneOf projects?

**Comment by TKilFree** [comment]
Thanks!

Yeah sorry I forgot to look at the framework version, I'll push an update in a moment for that.

I guess a separate nuget package would make sense given that if you're just using OneOf for C# it doesn't add anything to get this bundled in. Only issue is the code generated is relatively brittle if some things in the base OneOf package changes, so ideally the versioning and dependencies would reflect the tight coupling?

**Comment by mcintyre321** [comment]
If it's in my CI/CD process, it'll just publish a new package alongside the
other one with a matching version number.

**Comment by TKilFree** [comment]
Okay pushed an update to the .fsproj to make it a msbuild 15 style project + now supports .NET framework 4.5.1, and standard 1.6

Unfortunately even though the others are targeting 1.3, 1.6 seems like the lowest supported version by FSharp.Core

**Comment by mcintyre321** [comment]
Would there be any problems if I rename t the project/namespaces to `OneOf.FSharp` ?

**Comment by TKilFree** [comment]
No issues I can see, I didn't put any real thought into the names so feel free to change them to whatever you think works best.

**Comment by mcintyre321** [comment]
I've just renamed the project, and am getting an error:

```
---------------------------
Microsoft Visual Studio
---------------------------
Importing the file "C:\Users\Harry\OneDrive\stuff\OneOf\OneOf.FSharp\obj\OneOf.FSharp.fsproj.nuget.g.targets" into the file "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CrossTargeting.targets" results in a circular dependency.  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CrossTargeting.targets
---------------------------
OK   
---------------------------

```

any ideas? the changes are on master

**Comment by mcintyre321** [comment]
@TKilFree Hi, I finally got the build on Appveyor to work!

 https://www.nuget.org/packages/OneOf.fsharp

Is there any chance you could add some documentation on how to use it? I'm a bit rusty at F#

**Pull request merged**
