### PR TITLE
IL reduction

### LINKED ISSUE #72: Proposal: Save space by removing delegates from TryPick and Map autogenerated implementations
The autogenerated code for the `TryPickX` method currently looks like this:
```csharp
public OneOf<T0, T1, TResult, T3> MapT2<TResult>(Func<T2, TResult> mapFunc)
{
    if(mapFunc == null)
    {
        throw new ArgumentNullException(nameof(mapFunc));
    }
    return Match<OneOf<T0, T1, TResult, T3>>(
        input0 => input0,
        input1 => input1,
        input2 => mapFunc(input2),
        input3 => input3
    );
}
```
Each delegate requires the compiler to generate its own class. Similarly, for `Map`:
```csharp
public OneOf<T0, T1, TResult, T3> MapT2<TResult>(Func<T2, TResult> mapFunc)
{
    if(mapFunc == null)
    {
        throw new ArgumentNullException(nameof(mapFunc));
    }
    return Match<OneOf<T0, T1, TResult, T3>>(
        input0 => input0,
        input1 => input1,
        input2 => mapFunc(input2),
        input3 => input3
    );
}
```
Using autogenerated implementations that don't have delegates, e.g. for `TryPick`:
```csharp
public bool TryPickT1(out T1 value, out OneOf<T0, T2, T3, T4> remainder)
{
    value = IsT1 ? AsT1 : default;
    switch (_index)
    {
        case 0: remainder = OneOf<T0, T2, T3, T4>.FromT0(AsT0); break;
        case 1: remainder = default; break;
        case 2: remainder = OneOf<T0, T2, T3, T4>.FromT1(AsT2); break;
        case 3: remainder = OneOf<T0, T2, T3, T4>.FromT2(AsT3); break;
        case 4: remainder = OneOf<T0, T2, T3, T4>.FromT3(AsT4); break;
        default: throw new InvalidOperationException();
    }
    return IsT1;
}
```
and for `Map`
```csharp
public OneOf<T0, TResult, T2, T3, T4> MapT1<TResult>(Func<T1, TResult> mapFunc)
{
    if(mapFunc == null)
    {
        throw new ArgumentNullException(nameof(mapFunc));
    }
    switch (_index)
    {
        case 0: return OneOf<T0, TResult, T2, T3, T4>.FromT0(AsT0);
        case 1: return OneOf<T0, TResult, T2, T3, T4>.FromT1(mapFunc(AsT1));
        case 2: return OneOf<T0, TResult, T2, T3, T4>.FromT2(AsT2);
        case 3: return OneOf<T0, TResult, T2, T3, T4>.FromT3(AsT3);
        case 4: return OneOf<T0, TResult, T2, T3, T4>.FromT4(AsT4);
        default: throw new InvalidOperationException();
    }
}
```
reduces the file size, as follows:

| File | Current | Reduced |
| -- | -- | -- |
| OneOf.dll | 233K | 106K |
| OneOf.Extended.dll | 9.9M | 1.9M |

I've never had much need to consider this before, but I'm wondering if there are other ways to reduce the size of the IL? Maybe use later language features such as switch expressions? Or perhaps replace internal calls to `FromX` with a generic `FromIndex` method with a generic parameter?

How much of a reduction would be needed to move OneOf.Extended back into the original dll?

### LINKED ISSUE #73: Auto-generation code improvements
1. Move the code from a `.linq` file to an additional project under the solution. Will allow using IDE features and debugging without having to purchase a LINQPad license.
2. Set `LangVersion` in the `OneOf.csproj` and `OneOf.Extended.csproj` to `9.0`, and emit newer C# language syntax such as switch expressions. Note that for much of the syntax, a higher .NET TFM is not required.
3. Remove `for` and multiple `AppendLine` calls in an iteration; prefer a single `AppendLine` with joined strings.

### PR DESCRIPTION
**Pull request by zspitz**
Fix #72; fix #73

### CODE REVIEW

**Comment by zspitz** [comment]
@mcintyre321 Build is failing because of a relatively old version of MSBuild (15.9.21.664) which doesn't support later versions of C#; this is because AppVeyor is using the Visual Studio 2017 image. Can you upgrade to use the VS 2019 image, as described [here](https://www.appveyor.com/docs/build-environment/#build-worker-images)?

**Comment by mcintyre321** [comment]
Done, and I've retriggered your build.

It fails with `FSharp.Core 5.0.0 is not compatible with netstandard1.6`.

I don't mind if we move to netstandard2.0 TBH

**Comment by mcintyre321** [comment]
@zspitz I'm going to make a change on master before accepting this, to output multiple files (e.g. `OneOfT0.cs`,  `OneOfT1.cs`) for OneOf classes

If you can do the same in your branch, it will make Diffs much much better

**Comment by mcintyre321** [comment]
The files are called things like `OneOfT0.generated.cs` now

**Comment by mcintyre321** [comment]
https://github.com/mcintyre321/OneOf/pull/78/files#diff-2c5a3cdc2e7bcd682379382c0dba689520edfba582ec95758c8d6d380a14d74d

**Comment by zspitz** [comment]
I'm closing this PR, and splitting the fixes for #72 and #73 into separate PRs.

**Pull request closed without merging**
