### PR TITLE
Introducing Result and MapTX.

### PR DESCRIPTION
**Pull request by rtkelly13**
Had to implement Map with the argument to map from because the type inference rules struggle when the function is just named map.

### CODE REVIEW

**Comment by mcintyre321** [comment]
I've just had a play around with public static OneOf<T0, T1> From(T0 input)

	{
		return input;
	}

	public static OneOf<T0, T1> From(T1 input)
	{
		return input;
	}


and 

	public static OneOf<T0, T1> FromT0(T0 input)
	{
		return input;
	}

	public static OneOf<T0, T1> FromT1(T1 input)
	{
		return input;
	}

here: http://share.linqpad.net/3dvtu9.linq

It seems to me that `From` works just as well as `FromTx`, even if the types are interfaces or are shared.

In fact I feel like you've done something sneaky by using implicit operators with interfaces inside the `FromTx` methods. I thought the compiler or runtime wouldn't allow it, as you can't use an implicit against an interface directly!

Can you find any situations where the `From` is less safe than `FromTx`? I'd like to have the simplest api, but also the safest.

**Comment by rtkelly13** [comment]
I think I have found a case where it is an issue which is interfaces again... 
http://share.linqpad.net/eaaahd.linq

With regards to the use of implicit operators, it's more of a fault of the language more than anything else that they can't be attached to everything otherwise we wouldn't have the need for the From method. Plus from LOC perspective I could shorten each implementation down to `From(input) => input;` and I think that is a really nice way to avoid explicit construction of these objects again and fall through to the real implementation.

I am starting to think that actually, both approaches are equally valid, and the TX versions should be viewed as a fallback option but that does obviously balloon the amount of code in the library, Making the TX Versions of the methods would almost always be required as there lots of things that cannot be inferred but experimenting with the limits of the TXLess?!? versions and finding their limits and making sure people know there is a fallback version would be really nice.

**Comment by mcintyre321** [comment]
I guess we should go with the `Tx` methods - otherwise one day someone will use the `OneOf<IMetric, IImperial>.From(velocity)`, someone else will add `IImperial` to `velocity` and we'll read on the news that the new Mars rover has crashed for an unknown reason. 

Shame as `.From` reads nicer...

**Comment by rtkelly13** [comment]
Yeah think that is the safest case for the moment, I don't think including the `Tx` versions precludes any other versions as everyone has their own style of usage and `Map` and `From` could be added in the future with the understanding that there are ambiguous cases if they were well documented. 

Maybe letting the current implementation bed in a little bit if you are happy with the current changes and create another issue to experiment with the other versions would be best?

**Comment by mcintyre321** [comment]
OK I've pulled it in! Thanks!

**Comment by rtkelly13** [comment]
Thank you! I will give it a play and see how it goes!

**Pull request merged**
