### PR TITLE
Add async overloads for Match and Switch

### PR DESCRIPTION
**Pull request by michael-wolfenden**
Added async overloads `MatchAsync` and `SwitchAsync`

### CODE REVIEW

**Comment by rtkelly13** [comment]
@michael-wolfenden I think this looks like a great addition, I think one thing needs tweaking would be the usage of async for performance reasons.
I don't think I could cover it as well as this.
https://www.tabsoverspaces.com/233659-do-not-await-what-does-not-need-to-be-awaited

It would avoid the need to add ConfigureAwait(false) to this which would be required before allowing this change in.
https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f

@mcintyre321 
As an aside to this if Async is going to become natively supported by this lib where does this leave Map and the proposed Bind methods?

You would need 4 methods per TX!
for `OneOf<T0, T1>`

1. `OneOf<TResult, T1> MapT0(Func<T0, TResult> func)`
2. `Task<OneOf<TResult, T1>> MapAsyncT0(Func<T0, Task<TResult>> func)`

**Comment by michael-wolfenden** [comment]
Hey @rtkelly13, thanks for your response.

Your right , returning the `Task` directly rather than `awaiting` does increase performance as the compiler no longer has to generate the state machine.

However [there are ramifications to doing this](https://blog.stephencleary.com/2016/12/eliding-async-await.html) and Stephen Cleary has changed his recommendation to:

> Do not elide by default. Use the async and await for natural, easy-to-read code.

Having said that I'm happy to make the change to just return the `Task`s or leave as is and add `ConfigureAwait(false)` to all the awaits.

I did consider adding `MapAsync` but wasn't sure if the author wanted async methods in the first place and wanted to keep this pull request small. Happy to add these methods as well though.

**Comment by mcintyre321** [comment]
So I'm not adverse to this, but I think I must be missing something about why it's needed?

As far as I can tell
1. the Match code already works with async code, and 
2. if you want to use Switch, you can just use Match, and await the Task from the Match, and it behaves like a switch?

This is the unit test from the PR (in a linqpad script) with very minor modifications, against vanilla OneOf. Is there a better example of the pain point not having the async methods causes?
```
async Task Main()
{
	await MapAsync();
	await SwitchAsync();
	 
}

public async Task MapAsync()
{
	var resolvedDouble = await ResolveString(2.0);
	Assert.AreEqual("2", resolvedDouble);

	var resolvedInt = await ResolveString(4);
	Assert.AreEqual("4", resolvedInt);

	var resolvedString = await ResolveString("6");
	Assert.AreEqual("6", resolvedString);
}

public async Task SwitchAsync()
{
	await AssertSwitch(2.0, "2");
	await AssertSwitch(4, "4");
	await AssertSwitch("6", "6");
}

private async Task<string> ResolveString(OneOf<double, int, string> input)
	=> await input
		.MapT0(d => d.ToString(CultureInfo.InvariantCulture))
		.MapT1(i => i.ToString(CultureInfo.InvariantCulture))
		.Match(
			t1 => Task.FromResult(t1),
			t2 => Task.FromResult(t2),
			t3 => Task.FromResult(t3)
		);

private async Task AssertSwitch(OneOf<double, int, string> input, string expected)
	=> await input   //<
		.MapT0(d => d.ToString(CultureInfo.InvariantCulture))
		.MapT1(i => i.ToString(CultureInfo.InvariantCulture))
		.Match(
			async t1 =>
			{
				await Task.FromResult(0);
				Assert.AreEqual(expected, t1);
			},
			async t2 =>
			{
				await Task.FromResult(0);
				Assert.AreEqual(expected, t2);
			},
			async t3 =>
			{
				await Task.FromResult(0);
				Assert.AreEqual(expected, t3);
			}
		);
		
   
   
```

**Comment by michael-wolfenden** [comment]
@mcintyre321 I've done some more digging and your right. `Match` has a generic return type of `TResult` which could very well be a `Task<T>`.

Thanks for your response, feel free to close out this pull request.

**Comment by mcintyre321** [comment]
Thanks anyway, it's great to see people getting to grips with OneOf's innards!

**Comment by dzarda** [comment]
You see, it is technically *not required*. It would, however, make async-heavy code much more readable.

**Comment by mcintyre321** [comment]
@dzarda have you got an example of the code you are thinking of?

**Comment by dzarda** [comment]
Thank you for your answer and please excuse the delay. We employ the library in our hardware driver layers, hence the requirement for async/IO. Here is a real usage (redacted) implementing the following conceptual logic:

```
if (LampTurnOn()) {
  if (CameraTurnOn()) {
    return Success;
  }
  LampTurnOff()
  return Error;
}
return Error;
```

```cs
public async Task<OneOf<(IStoppable lamp, IStoppable cam), Error>> EnsureLampAndCameraRunning(AcquisitionSpecs<TCamSpecs> specs)
{
  var lampOnResult = await LampEnsureOn(specs.LampSpecs).ConfigureAwait(false);

  var bothRunningResult = await lampOnResult
    .Match(
    async lampStoppable =>
    {
      var cameraStreamingResult = await CameraEnsureStreaming(specs.CamSpecs).ConfigureAwait(false);
      return await cameraStreamingResult
        .Match(
        camStoppable => Task.FromResult<OneOf<(IStoppable lamp, IStoppable cam), Error>>((lampStoppable, camStoppable)),
        async camError =>
        {
          await lampStoppable.Stop().ConfigureAwait(false);
          return (OneOf<(IStoppable lamp, IStoppable cam), Error>)camError;
        });
    },
    error => Task.FromResult<OneOf<(IStoppable lamp, IStoppable cam), Error>>(error)).ConfigureAwait(false);

  return bothRunningResult;
}
```

Even the following straightforward example does exhibit the asymmetry with Success vs. Error paths (async lambda vs Task.FromResult()) https://dotnetfiddle.net/vb7blX

We're currently exploring ways of doing this and one possible solution is our extensions on the OneOf pattern, have you got an idea of better handling of such cases?

**Comment by mcintyre321** [comment]
I appreciate this may be dodging the question, but you can rewrite the whole thing as:

```
var lampOnResult = await LampEnsureOn(specs.LampSpecs).ConfigureAwait(false);
if (lampOnResult.TryPickT1(out Error lampOnError, out var lampStoppable))
{
	return lampOnError;	
}

var cameraStreamingResult = await CameraEnsureStreaming(specs.CamSpecs).ConfigureAwait(false);

if (cameraStreamingResult.TryPickT1(out Error cameraOnError, out var cameraStoppable))
{
	return lampOnError;
}

return (lampStoppable, cameraStoppable);

```

**Comment by mcintyre321** [comment]
I would also say it's a bit cleaner to put typename into the T of Match<T>:

public async Task<OneOf<(IStoppable lamp, IStoppable cam), Error>> EnsureLampAndCameraRunning(AcquisitionSpecs<TCamSpecs> specs)
	{
		var lampOnResult = await LampEnsureOn(specs.LampSpecs).ConfigureAwait(false);

		var bothRunningResult = await lampOnResult
		  .Match<Task<OneOf<(IStoppable lamp, IStoppable cam), Error>>>(
			  async lampStoppable =>
			  {
				  var cameraStreamingResult = await CameraEnsureStreaming(specs.CamSpecs).ConfigureAwait(false);
				  return await cameraStreamingResult
				  .Match<Task<OneOf<(IStoppable lamp, IStoppable cam), Error>>>(
				 	  async camStoppable => (lampStoppable, camStoppable),
					  async camError =>
					  {
						  await lampStoppable.Stop().ConfigureAwait(false);
						  return camError;
					  });
			  },
			  async error => error
		).ConfigureAwait(false);

		return bothRunningResult;
	}

```
and that can be made even clearer by using a Type alias for `OneOf<(IStoppable lamp, IStoppable cam), Error>`

**Pull request closed without merging**
